### ISSUE TITLE
Deprecate in favor of a regular yaml parser/generator.  Thoughts?

### ISSUE THREAD

**Issue by isaacs** [isaacs/yamlish#7]
(@rmg mostly for your input here)

I'm turning a bit of attention at getting node-tap to do nested/indented tests like perl's `Test::More` library.

In the meantime, it seems like there are a lot of edge cases in this yamlish thing, which could be avoided by just deprecating this and having tap use a performant and well-tested yaml library instead. (http://npm.im/js-yaml looks like the obvious choice).  When I wrote this module, there were no decent yaml parsers in JS, but times have changed.

Unless anyone strongly objects, I'll plan on dropping this dependency in tap@1.x and deprecating it then.

**Comment by rmg** [comment]
I think it makes sense.

Someone had the brilliant idea of not only listing dependants on npm, but listing repo urls on module pages, so we can get a pretty good idea of who else to ask :-)

These dependants have all seen at least one release in the last 9 months and their authors may have opinions or otherwise appreciate a heads up:
 * demobox - https://github.com/jaredly/demobox
 * eslint-tap - https://github.com/sindresorhus/eslint-tap
 * tap-eater - https://github.com/macbre/tap-eater
 * tap-unfunk - https://github.com/Bartvds/tap-unfunk 
 * tapr - https://github.com/jeffbski/tapper

I skipped the @ mentions for the above list to leave the decision up to you on pinging them yet or not.

These dependants are probably not worth pinging the authors about since their module is either "done", abandoned, or otherwise and would probably appreciate one less thing in their inbox:
 * fo3 - unknown
 * ios7crypt - https://github.com/mcandre/node-ios7crypt - last published 3 years ago
 * node-markdownblog - https://github.com/semu/node-markdownblog - last published 3 years ago
 * pop - https://github.com/alexyoung/pop - last published 2 years ago
 * tap - https://github.com/isaacs/node-tap - looks fresh, but I hear they're moving away from yamlish anyway..
 * tap_ - https://github.com/isaacs/node-tap - republish of tap by aredridel 2 years ago, accidental?
 * tap-harmony - https://github.com/ttaubert/node-tap-harmony - last published 2 years ago
 * taper - https://github.com/nylen/taper - last published 3 years ago

**Comment by fed135** [comment]
FYI, I made a benchmark project to compare your lib to js-yaml, and JSON (for fun)

https://github.com/fed135/yaml-benchmark

**Comment by isaacs** [comment]
This package isn't used by node-tap any more.  It uses js-yaml isntead.
